import { mkdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";
const generatedAt = new Date().toISOString();
const outDir = "artifacts/submission";

const commands = [
  { label: "Secret scan", args: ["run", "scan:secrets"] },
  { label: "Syntax check", args: ["run", "check:syntax"] },
  { label: "Block Kit constraints check", args: ["run", "check:block-kit"] },
  { label: "Slack UX proof", args: ["run", "slack:ux:proof"] },
  { label: "Slack interaction transcript", args: ["run", "slack:interactions:proof"] },
  { label: "Demo preview check", args: ["run", "demo:preview:check"] },
  { label: "Demo thumbnail check", args: ["run", "demo:thumbnail:check"] },
  { label: "Demo captions check", args: ["run", "demo:captions:check"] },
  { label: "Devpost form check", args: ["run", "devpost:form:check"] },
  { label: "Rules compliance check", args: ["run", "rules:check"] },
  { label: "Impact evaluation", args: ["run", "impact:evaluate"] },
  { label: "Recording readiness", args: ["run", "recording:check"] },
  { label: "Judge quickstart check", args: ["run", "judge:quickstart:check"] },
  { label: "Judge evidence matrix check", args: ["run", "judge:matrix:check"] },
  { label: "Bonus prize map check", args: ["run", "prize:check"] },
  { label: "Slack sandbox doctor", args: ["run", "sandbox:doctor"] },
  { label: "Unit tests", args: ["test"] },
  { label: "MCP smoke test", args: ["run", "smoke:mcp"] },
  { label: "MCP tool transcript", args: ["run", "mcp:transcript"] },
  { label: "Slack-to-MCP bridge smoke test", args: ["run", "smoke:slack-mcp"] },
  { label: "Fixture validation", args: ["run", "validate:fixtures"] },
  { label: "Public repo readiness", args: ["run", "repo:public:check"] },
  { label: "Live gate status", args: ["run", "submission:live-gates"] },
  { label: "Submission readiness", args: ["run", "submission:check"] },
  { label: "Demo asset export", args: ["run", "demo:assets"] }
];

function runCommand(step) {
  const startedAt = Date.now();
  const executable = process.platform === "win32" ? "cmd.exe" : npmCommand;
  const args = process.platform === "win32"
    ? ["/d", "/s", "/c", `${npmCommand} ${step.args.join(" ")}`]
    : step.args;
  const result = spawnSync(executable, args, {
    cwd: process.cwd(),
    encoding: "utf8"
  });
  const durationMs = Date.now() - startedAt;

  return {
    label: step.label,
    command: `${npmCommand} ${step.args.join(" ")}`,
    exitCode: result.status ?? 1,
    durationMs,
    stdout: normalizeOutput(result.stdout ?? ""),
    stderr: normalizeOutput(result.stderr ?? ""),
    passed: (result.status ?? 1) === 0
  };
}

function normalizeOutput(value) {
  return String(value)
    .replace(/\u001b\[[0-9;]*m/g, "")
    .replace(/✔/g, "PASS")
    .replace(/ℹ/g, "INFO")
    .replace(/âœ”/g, "PASS")
    .replace(/â„¹/g, "INFO")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?");
}

function tableEscape(value) {
  return String(value).replace(/\|/g, "/").replace(/\n/g, " ");
}

function outputBlock(result) {
  const output = [result.stdout.trim(), result.stderr.trim()].filter(Boolean).join("\n\n");
  return output || "(no output)";
}

function formatMarkdown(proof) {
  const rows = proof.commands.map((result) =>
    `| ${tableEscape(result.label)} | ${result.passed ? "PASS" : "FAIL"} | \`${tableEscape(result.command)}\` | ${result.durationMs} |`
  );

  const commandSections = proof.commands.map((result) => [
    `### ${result.label}`,
    "",
    `Command: \`${result.command}\``,
    `Result: ${result.passed ? "PASS" : "FAIL"} (${result.durationMs} ms)`,
    "",
    "```text",
    outputBlock(result),
    "```"
  ].join("\n"));

  return [
    "# SignalDesk Judge Proof Pack",
    "",
    `Generated: ${proof.generatedAt}`,
    "",
    "This file is generated by `npm.cmd run proof:pack`. It packages local evidence for judges and reviewers; it does not replace the live Slack sandbox demo.",
    "",
    "## Local Proof Summary",
    "",
    `Overall result: **${proof.localProofPassed ? "PASS" : "FAIL"}**`,
    "",
    "| Check | Result | Command | Duration ms |",
    "| --- | --- | --- | ---: |",
    ...rows,
    "",
    "## Judge-Visible Artifacts",
    "",
    "- `README.md`: project overview and judge test path.",
    "- `ARCHITECTURE.md` and `docs/architecture.svg`: architecture explanation and uploadable diagram.",
    "- `docs/devpost-copy.md`: Devpost-ready copy.",
    "- `docs/devpost-form.md`: exact Devpost form fields with external URL placeholders.",
    "- `docs/rules-compliance.md`: official rules-to-evidence map and manual final attestations.",
    "- `docs/judge-one-pager.md`: 30-second judge landing sheet with rubric proof and evidence boundary.",
    "- `docs/judge-quickstart.md`: shortest judge path from clone to repo-local proof and live sandbox gates.",
    "- `docs/impact-evaluation.md`: deterministic Agent for Good impact-readiness evaluation across synthetic nonprofit, school, clinic, and community fixtures.",
    "- `docs/judge-evidence-matrix.md`: rubric-to-evidence map for judges.",
    "- `docs/bonus-prize-map.md`: side-prize evidence map for Best UX, Most Innovative Slack Agent, and Best Technological Implementation.",
    "- `docs/slack-ux-proof.md`: App Home, help, modal, and safe-error Block Kit receipts.",
    "- `docs/slack-interaction-transcript.md`: Slack button and incident-channel interaction transcript.",
    "- `docs/mcp-tool-transcript.md`: full MCP tool-call transcript for every SignalDesk MCP tool.",
    "- `docs/github-repo-settings.md`: public repository metadata and launch checklist.",
    "- `docs/live-gate-handoff.md`: account-bound handoff for public repo, Slack sandbox, video upload, and Devpost URLs.",
    "- `docs/demo-script.md`, `docs/demo-captions.vtt`, `docs/demo-preview.png`, and `docs/video-package.md`: three-minute demo plan.",
    "- `docs/recording-readiness.md`: final recording preflight for proof moments, readable assets, and sandbox access reminders.",
    "- `docs/thumbnail.svg` and `docs/thumbnail.png`: 1280x720 demo thumbnail showing completed MCP-backed triage.",
    "- `docs/sample-incident-report.md`: evidence-gated report example.",
    "- `docs/slack-sandbox-runbook.md`: live Slack proof checklist.",
    "- `artifacts/submission/live-gate-status.md`: generated current-state packet for live external gates.",
    "- `artifacts/demo/incident-brief.json`: generated sample brief.",
    "- `artifacts/demo/slack-blocks.json`: generated Block Kit payload.",
    "- `artifacts/demo/incident-report.md`: generated Markdown report.",
    "",
    "## External Gates Still Required",
    "",
    "- Install SignalDesk in a Slack developer sandbox.",
    "- Record the live Slack demo video and make it public or unlisted.",
    "- Invite `slackhack@salesforce.com` and `testing@devpost.com` to the sandbox.",
    "- Add the public repository URL, demo video URL, and Slack sandbox URL to Devpost.",
    "",
    "## Command Evidence",
    "",
    ...commandSections,
    "",
    "## Evidence Boundary",
    "",
    "This proof pack validates repo-local behavior: tests, static preview labels, MCP stdio tools, fixture coverage, generated demo assets, and submission readiness checks. It does not prove Slack event delivery until the app is installed and exercised in the developer sandbox."
  ].join("\n");
}

mkdirSync(outDir, { recursive: true });

const commandResults = commands.map(runCommand);
const proof = {
  generatedAt,
  localProofPassed: commandResults.every((result) => result.passed),
  commands: commandResults,
  externalGatesRequired: [
    "Slack developer sandbox install",
    "judge sandbox access",
    "public or unlisted demo video URL",
    "public repository URL",
    "Devpost submission URL"
  ]
};

writeFileSync(`${outDir}/proof-pack.json`, `${JSON.stringify(proof, null, 2)}\n`);
writeFileSync("docs/judge-proof.md", `${formatMarkdown(proof)}\n`);

console.log(`Judge proof pack written to docs/judge-proof.md and ${outDir}/proof-pack.json`);

if (!proof.localProofPassed) {
  const failed = proof.commands.filter((result) => !result.passed).map((result) => result.label).join(", ");
  console.error(`Proof pack contains failed checks: ${failed}`);
  process.exitCode = 1;
}
